lang:
  not-player: <red>Only players can use this command!
  not-looking-at-block: <red>You must be looking at a block to use this command!
  jump-success: <green>Successfully Jumped to location!
  reloaded-config: <green>Successfully reloaded config!
options:
  range: 300
